// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Configuració General documents */
interface ConfiguracioGeneralDocumentData {
    /**
     * Slogan field in *Configuració General*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.slogan
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    slogan: prismicT.RichTextField;
    /**
     * Scroll field in *Configuració General*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.scroll
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    scroll: prismicT.RichTextField;
    /**
     * Contacta field in *Configuració General*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.contacta
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    contacta: prismicT.RichTextField;
    /**
     * Heading Footer field in *Configuració General*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.heading_footer
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_footer: prismicT.RichTextField;
    /**
     * Paràgraf Footer field in *Configuració General*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.paragraf_footer
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_footer: prismicT.RichTextField;
    /**
     * Copyright field in *Configuració General*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.copyright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    copyright: prismicT.RichTextField;
    /**
     * Slice Zone field in *Configuració General*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: configuracio_general.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ConfiguracioGeneralDocumentDataSlicesSlice>;
}
/**
 * Slice for *Configuració General → Slice Zone*
 *
 */
type ConfiguracioGeneralDocumentDataSlicesSlice = ContacteSlice;
/**
 * Configuració General document from Prismic
 *
 * - **API ID**: `configuracio_general`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfiguracioGeneralDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ConfiguracioGeneralDocumentData>, "configuracio_general", Lang>;
/** Content for Cooperativa documents */
interface CooperativaDocumentData {
    /**
     * Nom Pàgina field in *Cooperativa*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.nom_pagina
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    nom_pagina: prismicT.RichTextField;
    /**
     * Heading Homepage field in *Cooperativa*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.heading_homepage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_homepage: prismicT.RichTextField;
    /**
     * Paràgraf Homepage field in *Cooperativa*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.paragraf_homepage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_homepage: prismicT.RichTextField;
    /**
     * Heading Detall field in *Cooperativa*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.heading_detall
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_detall: prismicT.RichTextField;
    /**
     * Paràgraf Detall field in *Cooperativa*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.paragraf_detall
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_detall: prismicT.RichTextField;
    /**
     * Heading Qui Som field in *Cooperativa*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.heading_qui_som
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_qui_som: prismicT.RichTextField;
    /**
     * Slice Zone field in *Cooperativa*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: cooperativa.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<CooperativaDocumentDataSlicesSlice>;
}
/**
 * Slice for *Cooperativa → Slice Zone*
 *
 */
type CooperativaDocumentDataSlicesSlice = NosaltresSlice;
/**
 * Cooperativa document from Prismic
 *
 * - **API ID**: `cooperativa`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CooperativaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CooperativaDocumentData>, "cooperativa", Lang>;
/** Content for Estudi documents */
interface EstudiDocumentData {
    /**
     * Nom Pàgina field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.nom_pagina
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    nom_pagina: prismicT.RichTextField;
    /**
     * Heading Homepage field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.heading_homepage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_homepage: prismicT.RichTextField;
    /**
     * Paràgraf Homepage field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.paragraf_homepage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_homepage: prismicT.RichTextField;
    /**
     * Heading Detall field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.heading_detall
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_detall: prismicT.RichTextField;
    /**
     * Paràgraf Detall field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.paragraf_detall
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_detall: prismicT.RichTextField;
    /**
     * Heading Serveis field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.heading_serveis
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_serveis: prismicT.RichTextField;
    /**
     * Heading Clients field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.heading_clients
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_clients: prismicT.RichTextField;
    /**
     * Paràgraf Clients field in *Estudi*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.paragraf_clients
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_clients: prismicT.RichTextField;
    /**
     * Slice Zone field in *Estudi*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: estudi.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<EstudiDocumentDataSlicesSlice>;
}
/**
 * Slice for *Estudi → Slice Zone*
 *
 */
type EstudiDocumentDataSlicesSlice = ServeiSlice;
/**
 * Estudi document from Prismic
 *
 * - **API ID**: `estudi`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EstudiDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<EstudiDocumentData>, "estudi", Lang>;
/** Content for Pagina Projectes documents */
interface PaginaProjectesDocumentData {
    /**
     * Nom Pàgina field in *Pagina Projectes*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pagina_projectes.nom_pagina
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    nom_pagina: prismicT.RichTextField;
    /**
     * Heading Detall field in *Pagina Projectes*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pagina_projectes.heading_detall
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading_detall: prismicT.RichTextField;
    /**
     * Paràgraf Detall field in *Pagina Projectes*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pagina_projectes.paragraf_detall
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_detall: prismicT.RichTextField;
}
/**
 * Pagina Projectes document from Prismic
 *
 * - **API ID**: `pagina_projectes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PaginaProjectesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<PaginaProjectesDocumentData>, "pagina_projectes", Lang>;
/** Content for Proyecto documents */
interface ProyectoDocumentData {
    /**
     * Titol field in *Proyecto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: proyecto.titol
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titol: prismicT.RichTextField;
    /**
     * Client field in *Proyecto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: proyecto.client
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    client: prismicT.RichTextField;
    /**
     * Descripcio field in *Proyecto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: proyecto.descripcio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    descripcio: prismicT.RichTextField;
    /**
     * Any field in *Proyecto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: proyecto.any
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    any: prismicT.RichTextField;
    /**
     * body field in *Proyecto*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: proyecto.body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
    /**
     * Slice Zone field in *Proyecto*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: proyecto.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProyectoDocumentDataSlicesSlice>;
}
/**
 * Slice for *Proyecto → Slice Zone*
 *
 */
type ProyectoDocumentDataSlicesSlice = ImatgesSlice;
/**
 * Proyecto document from Prismic
 *
 * - **API ID**: `proyecto`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProyectoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ProyectoDocumentData>, "proyecto", Lang>;
export type AllDocumentTypes = ConfiguracioGeneralDocument | CooperativaDocument | EstudiDocument | PaginaProjectesDocument | ProyectoDocument;
/**
 * Primary content in Contacte → Primary
 *
 */
interface ContacteSliceDefaultPrimary {
    /**
     * Link field in *Contacte → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacte.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link: prismicT.RichTextField;
    /**
     * Text field in *Contacte → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacte.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for Contacte Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Contacte`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContacteSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContacteSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Contacte*
 *
 */
type ContacteSliceVariation = ContacteSliceDefault;
/**
 * Contacte Shared Slice
 *
 * - **API ID**: `contacte`
 * - **Description**: `Contacte`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContacteSlice = prismicT.SharedSlice<"contacte", ContacteSliceVariation>;
/**
 * Item in Imatges → Items
 *
 */
export interface ImatgesSliceDefaultItem {
    /**
     * Img field in *Imatges → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: imatges.items[].img
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img: prismicT.ImageField<never>;
}
/**
 * Default variation for Imatges Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Imatges`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImatgesSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ImatgesSliceDefaultItem>>;
/**
 * Slice variation for *Imatges*
 *
 */
type ImatgesSliceVariation = ImatgesSliceDefault;
/**
 * Imatges Shared Slice
 *
 * - **API ID**: `imatges`
 * - **Description**: `Imatges`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImatgesSlice = prismicT.SharedSlice<"imatges", ImatgesSliceVariation>;
/**
 * Primary content in Nosaltres → Primary
 *
 */
interface NosaltresSliceDefaultPrimary {
    /**
     * Nom field in *Nosaltres → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: nosaltres.primary.nom
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    nom: prismicT.RichTextField;
    /**
     * Carrec field in *Nosaltres → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: nosaltres.primary.carrec
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    carrec: prismicT.RichTextField;
    /**
     * Paràgraf field in *Nosaltres → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: nosaltres.primary.paragraf
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf: prismicT.RichTextField;
}
/**
 * Default variation for Nosaltres Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Nosaltres`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NosaltresSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NosaltresSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Nosaltres*
 *
 */
type NosaltresSliceVariation = NosaltresSliceDefault;
/**
 * Nosaltres Shared Slice
 *
 * - **API ID**: `nosaltres`
 * - **Description**: `Nosaltres`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NosaltresSlice = prismicT.SharedSlice<"nosaltres", NosaltresSliceVariation>;
/**
 * Primary content in Servei → Primary
 *
 */
interface ServeiSliceDefaultPrimary {
    /**
     * Titol Servei field in *Servei → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: servei.primary.titol_servei
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titol_servei: prismicT.RichTextField;
    /**
     * Paràgraf Servei field in *Servei → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: servei.primary.paragraf_servei
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraf_servei: prismicT.RichTextField;
}
/**
 * Item in Servei → Items
 *
 */
export interface ServeiSliceDefaultItem {
    /**
     * Servei field in *Servei → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: servei.items[].servei
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    servei: prismicT.RichTextField;
}
/**
 * Default variation for Servei Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Servei`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServeiSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ServeiSliceDefaultPrimary>, Simplify<ServeiSliceDefaultItem>>;
/**
 * Slice variation for *Servei*
 *
 */
type ServeiSliceVariation = ServeiSliceDefault;
/**
 * Servei Shared Slice
 *
 * - **API ID**: `servei`
 * - **Description**: `Servei`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServeiSlice = prismicT.SharedSlice<"servei", ServeiSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ConfiguracioGeneralDocumentData, ConfiguracioGeneralDocumentDataSlicesSlice, ConfiguracioGeneralDocument, CooperativaDocumentData, CooperativaDocumentDataSlicesSlice, CooperativaDocument, EstudiDocumentData, EstudiDocumentDataSlicesSlice, EstudiDocument, PaginaProjectesDocumentData, PaginaProjectesDocument, ProyectoDocumentData, ProyectoDocumentDataSlicesSlice, ProyectoDocument, AllDocumentTypes, ContacteSliceDefaultPrimary, ContacteSliceDefault, ContacteSliceVariation, ContacteSlice, ImatgesSliceDefaultItem, ImatgesSliceDefault, ImatgesSliceVariation, ImatgesSlice, NosaltresSliceDefaultPrimary, NosaltresSliceDefault, NosaltresSliceVariation, NosaltresSlice, ServeiSliceDefaultPrimary, ServeiSliceDefaultItem, ServeiSliceDefault, ServeiSliceVariation, ServeiSlice };
    }
}
