// Code generated by Slice Machine. DO NOT EDIT.

import Contacte from './Contacte';
import Imatges from './Imatges';
import Nosaltres from './Nosaltres';
import Servei from './Servei';

export {
	Contacte,
	Imatges,
	Nosaltres,
	Servei,
};

export const components = {
	contacte: Contacte,
	imatges: Imatges,
	nosaltres: Nosaltres,
	servei: Servei,
};
